# Generated by Django 5.2.1 on 2025-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
